/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import Classdoc.DBConnection;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Neeraj
 */
public class Account extends javax.swing.JPanel {

    /**
     * Creates new form account
     */

    public Account(Dimension dim) {
        initComponents();
        this.setSize(dim);
        ccb.addItem(" ");
        try
        {
        String b,c,d,e;
        b="Select * from customer_details order by cname";
        rs=DBConnection.executeQuery(b);
        while(rs.next())
         {
        c=rs.getString("cname");
        ccb.addItem(c);
       }

        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage()+" msg of upper");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtr = new javax.swing.JTextField();
        txtc = new javax.swing.JTextField();
        txtgot = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        ccb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtm = new javax.swing.JTextField();
        txtcid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txttax = new javax.swing.JTextField();
        ctax = new javax.swing.JTextField();
        ccommission = new javax.swing.JTextField();
        creceived = new javax.swing.JTextField();
        csales = new javax.swing.JTextField();
        cr = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t1 = new com.github.lgooddatepicker.components.DatePicker();
        t2 = new com.github.lgooddatepicker.components.DatePicker();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        Title = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Select date");
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jButton1.setText("Calculate");
        jButton1.setBackground(new java.awt.Color(54, 33, 89));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel2.setText("From");
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setText("To");
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        txtsales.setEditable(false);
        txtsales.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtsales, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, -1));

        jLabel5.setText("Sales");
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel6.setText("Remaining");
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel7.setText("TotalCommission");
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jLabel8.setText("Received");
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        txtr.setEditable(false);
        txtr.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 70, -1));

        txtc.setEditable(false);
        txtc.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 70, -1));

        txtgot.setEditable(false);
        txtgot.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 70, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1070, 10));

        jLabel4.setText("CustomerName");
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 126, -1));

        ccb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ccbItemStateChanged(evt);
            }
        });
        jPanel1.add(ccb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 100, -1));

        jLabel9.setText("Cid");
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jLabel10.setText("Mobile");
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        txtm.setEditable(false);
        txtm.setBackground(java.awt.Color.lightGray);
        jPanel1.add(txtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 119, -1));

        txtcid.setEditable(false);
        txtcid.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 70, -1));

        jButton2.setText("FIND");
        jButton2.setBackground(new java.awt.Color(53, 33, 89));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoiceno", "Invoicedate", "Paymentdate", "PaymentType", "Referenceno", "AmountPaid", "Discount", "GST", "Totalamount", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 1000, 183));

        jLabel11.setText("Sales");
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jLabel12.setText("Remaining");
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        jLabel13.setText("Commission");
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, -1, -1));

        jLabel14.setText("Received");
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 70, -1));

        jLabel15.setText("TotalTax");
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, -1, -1));

        txttax.setEditable(false);
        txttax.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txttax, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 100, -1));

        ctax.setEditable(false);
        ctax.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(ctax, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 106, -1));

        ccommission.setEditable(false);
        ccommission.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(ccommission, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 108, -1));

        creceived.setEditable(false);
        creceived.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(creceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 108, -1));

        csales.setEditable(false);
        csales.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(csales, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 108, -1));

        cr.setEditable(false);
        cr.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(cr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 108, -1));

        jLabel16.setText("Tax");
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, -1, -1));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator9.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1020, 10));

        jSeparator10.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator10.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 1020, 10));

        jSeparator11.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator11.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 10, 420));

        jSeparator12.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator12.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 20, 420));

        jLabel17.setText(" Company Sales");
        jLabel17.setAlignmentX(0.5F);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 80, 20));

        jSeparator13.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator13.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 1020, 20));

        jSeparator14.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator14.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1020, 20));

        jSeparator15.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator15.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, 20, 160));

        jSeparator16.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator16.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 10, 160));

        Title.setBackground(new java.awt.Color(54, 33, 89));
        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boss.png"))); // NOI18N
        Title.setText("Accounts");
        Title.setOpaque(true);
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1070, 60));

        jLabel18.setText(" Company  Sales");
        jLabel18.setAlignmentX(0.5F);
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 20));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
Connection con;
ResultSet rs;
Statement st;
String sql;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
            st=con.createStatement();
            sql="Select * from payment where invoicedate between ' "+t1.getDateStringOrSuppliedString("yyyy-mm-dd")+" 'and' "+t2.getDateStringOrSuppliedString("yyyy-mm-dd")+ " ' ";  //t1 and t2 are dates
            System.out.println(""+sql);
            rs=st.executeQuery(sql);
            double a,b,c,d,e,sumofpay=0.0,sumofamt=0.0,sumofbalance=0.0,sumofcom=0.0,sumoftax=0.0;

            while(rs.next())
            {
                a=rs.getDouble("amountpaid");
                b=rs.getDouble("actualamount");
                c=rs.getDouble("balance");
                d=rs.getDouble("commission");
                e=rs.getDouble("tax");
                sumofpay=sumofpay+a;          //amount paid by the user,s
                sumofamt=sumofamt+b;         //actual amount
                sumofbalance=sumofbalance+c; //remaining amount which user has to pay
                sumofcom=sumofcom+d;
                sumoftax=sumoftax+e;
            }
            txtsales.setText(""+sumofamt);
            txtr.setText(""+sumofbalance);
            txtc.setText(""+sumofcom);
            txtgot.setText(""+sumofpay);
            txttax.setText(""+sumoftax);
        }
        catch(Exception ex)
        {
            System.out.println(""+ex.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ccbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ccbItemStateChanged
        String b,e,f,d;
        int c;
        e=(String) ccb.getSelectedItem();
        try
        {

            b="Select mobile_no,cid from customer_details where cname ='"+e+"'";
            rs=DBConnection.executeQuery(b);
            while(rs.next())
            {
                d=rs.getString("mobile_no");
                c=rs.getInt("cid");
                txtcid.setText(""+c);
                txtm.setText(""+d);
            }

        }
        catch(Exception ex)
        {

            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ccbItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel t1=(DefaultTableModel)jTable1.getModel();
        String b,c,d,e;
        int a;
        double f,g,h,i,j,k;
        try
        {
            double sumofpay=0.0,sumofamt=0.0,sumofbalance=0.0,sumofcom=0.0,sumoftax=0.0;
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
            st=con.createStatement();
            sql="Select * from payment where cid ='"+txtcid.getText()+"';";
            ResultSet rs1=st.executeQuery(sql);
            System.out.println(""+sql);
            while(rs1.next())
            {
                a=rs1.getInt("invoiceno");
                b=rs1.getDate("invoicedate").toString();
                c=rs1.getDate("paymentdate").toString();
                d=rs1.getString("paymenttype");
                e=rs1.getString("referenceno");
                f=rs1.getDouble("amountpaid");
                g=rs1.getDouble("discount");
                h=rs1.getDouble("tax");
                i=rs1.getDouble("actualamount");
                j=rs1.getDouble("balance");
                k=rs1.getDouble("commission");
                t1.addRow(new Object[]{a,b,c,d,e,f,g,h,i,j});
                sumofpay=sumofpay+f;          //amount paid by the user,s
                sumofamt=sumofamt+i;         //actual amount
                sumofbalance=sumofbalance+j; //remaining amount which user has to pay
                sumofcom=sumofcom+k;
                sumoftax=sumoftax+h;
            }
            csales.setText(""+sumofamt);
            ccommission.setText(""+sumofcom);
            ctax.setText(""+sumoftax);
            cr.setText(""+sumofbalance);
            creceived.setText(""+sumofpay);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex);
            System.out.println("erroe msg"+ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JComboBox<String> ccb;
    private javax.swing.JTextField ccommission;
    private javax.swing.JTextField cr;
    private javax.swing.JTextField creceived;
    private javax.swing.JTextField csales;
    private javax.swing.JTextField ctax;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private com.github.lgooddatepicker.components.DatePicker t1;
    private com.github.lgooddatepicker.components.DatePicker t2;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtgot;
    private javax.swing.JTextField txtm;
    private javax.swing.JTextField txtr;
    private javax.swing.JTextField txtsales;
    private javax.swing.JTextField txttax;
    // End of variables declaration//GEN-END:variables
}
