/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classdoc.DBConnection;
import Classdoc.Dim;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class airticket extends javax.swing.JPanel {

    /**
     * Creates new form airticket
     */
    public airticket(Dimension dim,String user) {
        initComponents();
        this.setSize(dim);
        txtinvoiceno.setText("" + new Dim().createInvoice());
        txtuser.setText(user);
        jScrollPane1.setVisible(true);
        jPanel1.setVisible(true);
        ccb.addItem(" ");
        cbm.addItem(" ");
        try
        {
        String b,c,d,e;
        b="Select * from customer_details";
        rs=DBConnection.executeQuery(b);
        while(rs.next())
         {
        c=rs.getString("cname");
        ccb.addItem(c);
       }

        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage()+" msg of upper");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbcity = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcost = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        txtsource = new javax.swing.JTextField();
        txtgrosstotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        txttax = new javax.swing.JTextField();
        txttotalamount = new javax.swing.JTextField();
        txtdestination = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtairlinename = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cbairlinetype = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cbpass = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtinvoiceno = new javax.swing.JTextField();
        ccb = new javax.swing.JComboBox<>();
        txtcid = new javax.swing.JTextField();
        cbm = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtpeople = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtflightno = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtc = new javax.swing.JTextField();
        txtinvoicedate = new com.github.lgooddatepicker.components.DatePicker();
        txtdeparture = new com.github.lgooddatepicker.components.DatePicker();
        txtarrival = new com.github.lgooddatepicker.components.DatePicker();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Invoiceno");
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel2.setText("Invoice date");
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel3.setText("Customer");
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel4.setText("Mobileno");
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel6.setText("City");
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel9.setText("No of people");
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 269, -1, 20));

        cbcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bhopal", "Delhi", "Agra", "Surat", " " }));
        jPanel1.add(cbcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, -1));

        jLabel10.setText("Departure Date");
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        jLabel11.setText("Arrival date");
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jLabel12.setText("From");
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));

        jLabel13.setText("To");
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 20, 20));
        jPanel1.add(txtcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 110, -1));

        txtamount.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 100, -1));
        jPanel1.add(txtsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 110, -1));

        txtgrosstotal.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtgrosstotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 600, 100, 20));

        jLabel14.setText("Gross total");
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 600, -1, -1));

        jLabel15.setText("Discount total");
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, -1, 20));

        jLabel16.setText("Tax total");
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, -1, 20));

        jLabel17.setText("Amount payable");
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, -1, -1));
        jPanel1.add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 100, 20));
        jPanel1.add(txttax, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 100, 20));

        txttotalamount.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txttotalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 100, -1));
        jPanel1.add(txtdestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 110, -1));

        jLabel18.setText("Airline name");
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));
        jPanel1.add(txtairlinename, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 110, -1));

        jLabel19.setText("Airline Type");
        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 90, -1));

        cbairlinetype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domestic", "International", " " }));
        jPanel1.add(cbairlinetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 110, -1));

        jLabel20.setText("Boarding pass");
        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 100, -1));

        cbpass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "First Class" }));
        jPanel1.add(cbpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 110, -1));

        jLabel21.setText("CustomerID");
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtinvoiceno.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtinvoiceno, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 110, -1));

        ccb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ccbItemStateChanged(evt);
            }
        });
        ccb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccbActionPerformed(evt);
            }
        });
        jPanel1.add(ccb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 120, -1));

        txtcid.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 120, -1));

        cbm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmItemStateChanged(evt);
            }
        });
        jPanel1.add(cbm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline name", "Type", "Flightno", "BoardingPass", "Person/s", "From", "To", "Departure Date", "Arrival Date", "City", "Price", "Amount"
            }
        ));
        jTable1.setRowHeight(20);
        jScrollPane4.setViewportView(jTable1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1030, 120));

        jButton2.setText("Confirm");
        jButton2.setBackground(new java.awt.Color(53, 33, 89));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, -1, -1));

        jButton3.setText("Insert");
        jButton3.setBackground(new java.awt.Color(53, 33, 89));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 100, -1));

        jButton4.setText("Add Row");
        jButton4.setBackground(new java.awt.Color(53, 33, 89));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 360, 110, -1));

        jButton5.setText("Clear");
        jButton5.setBackground(new java.awt.Color(53, 33, 89));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 360, 90, -1));

        jLabel22.setText("Cost");
        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 30, -1));
        jPanel1.add(txtpeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 120, -1));

        jLabel23.setText("Flight no");
        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel7.setText("Amount");
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, -1, -1));
        jPanel1.add(txtflightno, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 110, -1));

        jButton6.setText("Calculate");
        jButton6.setBackground(new java.awt.Color(53, 33, 89));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        jLabel8.setText("User");
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        txtuser.setBackground(new java.awt.Color(204, 204, 204));
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 110, -1));

        jButton7.setText("Remove Row");
        jButton7.setBackground(new java.awt.Color(53, 33, 89));
        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 360, 140, -1));

        jLabel24.setText("Commission");
        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));
        jPanel1.add(txtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 100, 20));
        jPanel1.add(txtinvoicedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 160, -1));
        jPanel1.add(txtdeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 140, -1));
        jPanel1.add(txtarrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator9.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1020, 10));

        jSeparator10.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator10.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1020, 10));

        jSeparator11.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator11.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 20, 290));

        jSeparator12.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator12.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 290));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
Connection con =null;
 ResultSet  rs= null ;
 Statement st=null;
String sql;
    private void ccbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccbActionPerformed
    }//GEN-LAST:event_ccbActionPerformed

    private void ccbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ccbItemStateChanged
        String b,e,f;
         int c,d;
         cbm.removeAllItems();
        e=(String) ccb.getSelectedItem(); 
        try
        {
         b="Select mobile_no from customer_details where cname ='"+e+"'";
        rs=DBConnection.executeQuery(b);
         while(rs.next())
         {
         f=rs.getString("mobile_no");
         cbm.addItem(f);
        }
         
}
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
 
    }//GEN-LAST:event_ccbItemStateChanged

    private void cbmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmItemStateChanged
String b,e,f;
         int c,d;
        e=(String) cbm.getSelectedItem(); 
        try
        {
       b="Select cid from customer_details where mobile_no ='"+e+"'";
        rs=DBConnection.executeQuery(b);
         while(rs.next())
         {
         c=rs.getInt("cid");
         txtcid.setText(""+c);
          }
         }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
      
    }//GEN-LAST:event_cbmItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultTableModel t=(DefaultTableModel)jTable1.getModel(); 
 String a,b,c,d,e,f,g,h,i,j,k,l,m;
 a=txtairlinename.getText();
 b=cbairlinetype.getSelectedItem().toString();
 c=cbpass.getSelectedItem().toString();
 d=txtflightno.getText();
 e=txtpeople.getText();
 f=txtsource.getText();
 g=txtdestination.getText();
 h=txtdeparture.getDateStringOrSuppliedString("yyyy-mm-dd");
 i=txtarrival.getDateStringOrSuppliedString("yyyy-mm-dd");
 j=cbcity.getSelectedItem().toString();
// k=txtaddress.getText();
 l=txtcost.getText();
 int amt=Integer.parseInt(l)*Integer.parseInt(e);
 txtamount.setText(""+amt);
 int sum=0;
         t.addRow(new Object[]{a,b,c,d,e,f,g,h,i,j,l,amt});
         int row=jTable1.getRowCount();
         for(int p=0;p<row;p++)
         {
         amt=Integer.parseInt((t.getValueAt(p,11)).toString());
      sum=sum+amt;
         }
         txtgrosstotal.setText(""+sum);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     DefaultTableModel t=(DefaultTableModel)jTable1.getModel(); 
     t.addRow(new Object[]{});
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

clear(); //   function defined below     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        double a,b,c,d,e;
        a=Double.parseDouble(txtgrosstotal.getText());
        b=Double.parseDouble(txtdiscount.getText());
        c=Double.parseDouble(txttax.getText());
        e=Double.parseDouble(txtc.getText());
        d=a+c-b;
        txttotalamount.setText(""+d);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
payment();
        airline();
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        DefaultTableModel t=(DefaultTableModel)jTable1.getModel();  
try
{
 int row=jTable1.getRowCount();
 --row;
t.removeRow(row);
}
catch(Exception e1)
{
JOptionPane.showMessageDialog(null, e1.getMessage());
}
    }//GEN-LAST:event_jButton7ActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbairlinetype;
    private javax.swing.JComboBox<String> cbcity;
    private javax.swing.JComboBox<String> cbm;
    private javax.swing.JComboBox<String> cbpass;
    private javax.swing.JComboBox<String> ccb;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtairlinename;
    private javax.swing.JTextField txtamount;
    private com.github.lgooddatepicker.components.DatePicker txtarrival;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcost;
    private com.github.lgooddatepicker.components.DatePicker txtdeparture;
    private javax.swing.JTextField txtdestination;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtflightno;
    private javax.swing.JTextField txtgrosstotal;
    private com.github.lgooddatepicker.components.DatePicker txtinvoicedate;
    private javax.swing.JTextField txtinvoiceno;
    private javax.swing.JTextField txtpeople;
    private javax.swing.JTextField txtsource;
    private javax.swing.JTextField txttax;
    private javax.swing.JTextField txttotalamount;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
public  void clear()
{
 txtairlinename.setText("");
 txtflightno.setText("");
 txtpeople.setText("");
 txtsource.setText("");
 txtdestination.setText("");
 txtdeparture.setText("");
 txtarrival.setText("");
// txtaddress.setText("");
 txtcost.setText("");
 txtamount.setText("");
 txtdiscount.setText("");
 txttax.setText("");
 txtc.setText("");
 txttotalamount.setText("");
 txtgrosstotal.setText("");
}
public void payment()
{
try
{
    double comm,amt;
    amt=Double.parseDouble(txtgrosstotal.getText());
    comm=Double.parseDouble(txtc.getText());
 Class.forName("java.sql.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
      st=con.createStatement();     
      sql="Insert into payment(invoiceno,invoicedate,cid,customername,actualamount,balance,user,discount,tax,commission) values('"+txtinvoiceno.getText()+"','"+txtinvoicedate.getDateStringOrSuppliedString("yyyy-mm-dd")+"','"+txtcid.getText()+"','"+ccb.getSelectedItem()+"','"+txttotalamount.getText()+"','"+txttotalamount.getText()+"','"+txtuser.getText()+"','"+txtdiscount.getText()+"','"+txttax.getText()+"','"+comm+"');";
      System.out.println(""+sql);
 st.executeUpdate(sql);
}
catch(Exception ex)
{
    System.out.println(""+ex.getMessage());
}
}

public void airline()
{
try
{
    Class.forName("java.sql.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
      st=con.createStatement();
      DefaultTableModel t=(DefaultTableModel)jTable1.getModel();  
      int row=jTable1.getRowCount();
      for(int i=0;i<row;i++)
      {
  sql="Insert into airline values('"+txtinvoiceno.getText()+"','"+txtinvoicedate.getDateStringOrSuppliedString("yyyy-mm-dd")+"','"+txtcid.getText()+"','"+t.getValueAt(i,0)+"','"+t.getValueAt(i,1)+"','"+t.getValueAt(i,2)+"','"+t.getValueAt(i,3)+"','"+t.getValueAt(i,4)+"','"+t.getValueAt(i,5)+"','"+t.getValueAt(i,6)+"','"+t.getValueAt(i,7)+"','"+t.getValueAt(i,8)+"','"+t.getValueAt(i,9)+"','"+t.getValueAt(i,10)+"','"+t.getValueAt(i,11)+"','"+" "+"','"+" "+"');";
 System.out.println(""+sql);
 st.executeUpdate(sql);
      }
}
catch(Exception ex)
{
    System.out.println(""+ex.getMessage());
}

}
}
