/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classdoc.DBConnection;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author Neeraj
 */
public class CustLead extends javax.swing.JPanel {

    /**
     * Creates new form CustLead
     */
    public CustLead(String user,Dimension dim)
    {
        this();
        txtUser.setText(user);
        txtLeadno.setText(getNewLead()+"");
    }
    
    public CustLead() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel52 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtDate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel40 = new javax.swing.JLabel();
        txtLeadno = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        cbAirTicket = new javax.swing.JCheckBox();
        cbRailwayTicket = new javax.swing.JCheckBox();
        cbHotel = new javax.swing.JCheckBox();
        cbVehicle = new javax.swing.JCheckBox();
        cbVise = new javax.swing.JCheckBox();
        cbPassport = new javax.swing.JCheckBox();
        cbInsurance = new javax.swing.JCheckBox();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtInfant = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtChild = new javax.swing.JTextField();
        txtAdult = new javax.swing.JTextField();
        txtDays = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtFrom = new com.github.lgooddatepicker.components.DatePicker();
        txtTo = new com.github.lgooddatepicker.components.DatePicker();
        txtUser = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtPriority = new javax.swing.JComboBox<>();
        jLabel55 = new javax.swing.JLabel();
        txtRef_account = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        txtPasson = new javax.swing.JTextField();
        txtReference = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel52.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 51));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 140, -1));

        jLabel38.setText("No. of days");
        jLabel38.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, -1, -1));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel40.setText("Lead Number:");
        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 20));

        txtLeadno.setEditable(false);
        txtLeadno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeadnoActionPerformed(evt);
            }
        });
        add(txtLeadno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, -1));

        jLabel41.setText("Services:");
        jLabel41.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, -1));

        jLabel42.setText("Mobile Number:");
        jLabel42.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });
        add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, -1));

        jLabel43.setText("E-Mail:");
        jLabel43.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel44.setText("Traveller Name:");
        jLabel44.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 320, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbAirTicket.setText("Air Ticket");
        cbAirTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAirTicketActionPerformed(evt);
            }
        });

        cbRailwayTicket.setText("Railway Ticket");

        cbHotel.setText("Hotel");

        cbVehicle.setText("Vehicle");

        cbVise.setText("Vise");

        cbPassport.setText("Passport");

        cbInsurance.setText("Insurance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbHotel)
                            .addComponent(cbVise))
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbInsurance)
                            .addComponent(cbRailwayTicket)
                            .addComponent(cbVehicle))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbAirTicket)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(cbPassport)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAirTicket)
                    .addComponent(cbRailwayTicket))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHotel)
                    .addComponent(cbVehicle))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVise)
                    .addComponent(cbInsurance))
                .addGap(18, 18, 18)
                .addComponent(cbPassport)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 320, 210));

        jLabel45.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 51, 51));
        jLabel45.setText("City:");
        add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel46.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 51, 51));
        jLabel46.setText("Address:");
        add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel47.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setText("Date:");
        add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel39.setText("User:");
        jLabel39.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        txtInfant.setText("0");
        txtInfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInfantActionPerformed(evt);
            }
        });
        txtInfant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInfantKeyReleased(evt);
            }
        });
        add(txtInfant, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 90, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 140, -1));

        txtChild.setText("0");
        txtChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChildActionPerformed(evt);
            }
        });
        txtChild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChildKeyReleased(evt);
            }
        });
        add(txtChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 100, -1));

        txtAdult.setText("0");
        txtAdult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdultActionPerformed(evt);
            }
        });
        txtAdult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdultKeyReleased(evt);
            }
        });
        add(txtAdult, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 90, -1));

        txtDays.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDaysFocusGained(evt);
            }
        });
        txtDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDaysActionPerformed(evt);
            }
        });
        add(txtDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 90, -1));

        jLabel48.setText("Total");
        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, -1));

        jLabel49.setText("Infant");
        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, -1));

        jLabel50.setText("Child");
        jLabel50.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));
        add(txtFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 140, -1));

        txtTo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtToFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToFocusLost(evt);
            }
        });
        txtTo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtToMouseExited(evt);
            }
        });
        add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        txtUser.setEditable(false);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 90, -1));

        jLabel51.setText("Adult");
        jLabel51.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jLabel53.setText("To");
        jLabel53.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jLabel54.setText("From");
        jLabel54.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        txtPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Medium", "Low" }));
        add(txtPriority, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 290, -1));

        jLabel55.setText("Priority");
        jLabel55.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));
        add(txtRef_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 290, -1));

        jLabel56.setText("Passon to");
        jLabel56.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));
        add(txtPasson, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 290, -1));
        add(txtReference, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 290, -1));

        jLabel58.setText("Reference Account");
        jLabel58.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 290, 90));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel57.setText("Next >");
        jLabel57.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel57)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 80, 40));

        jLabel59.setText("Reference");
        jLabel59.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel60.setText("Cancel");
        jLabel60.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel60)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, -1, -1));

        txtTotal.setText("0");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 90, -1));

        jLabel61.setText("Notes");
        jLabel61.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(51, 51, 51));
        add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, 190, 20));
    }// </editor-fold>//GEN-END:initComponents
int lead,adult,child,infant,total,days;
String date,mobile,email,name,city,address,service="",from,to,priority,passonto,reference,ref_account,user,notes;
    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtLeadnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeadnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeadnoActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void cbAirTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAirTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAirTicketActionPerformed

    private void txtInfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInfantActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChildActionPerformed

    private void txtAdultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdultActionPerformed

    private void txtDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDaysActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        //if days not calcuated before
        try{
        Date d1=new SimpleDateFormat("yyyy-mm-dd").parse(from=txtFrom.getDateStringOrSuppliedString("yyyy-mm-dd"));
        Date d2=new SimpleDateFormat("yyyy-mm-dd").parse(to=txtTo.getDateStringOrSuppliedString("yyyy-mm-dd"));
        txtDays.setText(ChronoUnit.DAYS.between(d1.toInstant(),d2.toInstant())+"");    
        }
        catch(Exception e)
        {
            System.out.println("date exception");
        }
        
        
        lead=Integer.parseInt(txtLeadno.getText());
        date=txtDate.getDateStringOrSuppliedString("yyyy-mm-dd");
        mobile=txtMobile.getText();
        email=txtEmail.getText();
        name=txtName.getText();
        city=txtCity.getText();
        address=txtAddress.getText();
        user=txtUser.getText();
        priority=txtPriority.getSelectedItem().toString();
        passonto=txtPasson.getText();
        reference=txtReference.getText();
        ref_account=txtRef_account.getText();
        notes=txtNotes.getText();
               
        if(mobile.length()==0 ||email.length()==0 || name.length()==0 || email.length()==0 || name.length()==0 ||city.length()==0
                || address.length()==0 || user.length()==0 || passonto.length()==0 || reference.length()==0 || ref_account.length()==0
                        || txtAdult.getText().length()==0 || txtChild.getText().length()==0 || txtInfant.getText().length()==0)
                        {
                            jLabel1.setText("All fields are compulsary");
                            return;
                        }
        
        
        try{
        adult=Integer.parseInt(txtAdult.getText());
        child=Integer.parseInt(txtChild.getText());
        infant=Integer.parseInt(txtInfant.getText());
        total=Integer.parseInt(txtTotal.getText());
        from=txtFrom.getDateStringOrSuppliedString("yyyy-mm-dd");
        to=txtTo.getDateStringOrSuppliedString("yyyy-mm-dd");
        
        days=Integer.parseInt(txtDays.getText());
        }
        catch(NumberFormatException e)
        {
            jLabel1.setText(e.getMessage());
            return;
        }
        if(from.equals("yyyy-mm-dd"))
        {
            jLabel1.setText("Enter valid date");
            return;
        }
        jLabel1.setText("");

        //services
        if(cbAirTicket.isSelected())
        service=service+"Air";
        
        if(cbRailwayTicket.isSelected())
        service=service+"Railway";
        
        if(cbHotel.isSelected())
        service=service+"Hotel";
        
        if(cbVehicle.isSelected())
        service=service+"Vehicle";
        
        if(cbVise.isSelected())
        service=service+"Vise";
        
        if(cbPassport.isSelected())
        service=service+"Passport";
        
        if(cbInsurance.isSelected())
        service=service+"Insurance";
        
       
        String sql=String.format("insert into lead_details values(%s,'%s','%s','%s','%s','%s','%s','%s','%s',%s,%s,%s,'%s','%s',%s,'%s','%s','%s','%s','%s')", lead,date,mobile,email,name,city,address,service,user,adult,child,infant,from,to,days,priority,passonto,reference,ref_account,notes);
        System.out.println(sql);
        try{
        int result=DBConnection.executeUpdate(sql);
        if(result<1)
        {
            System.out.println("something went wrong");
                return;
        }
        
        }
        catch(Exception e)
        {
            System.out.println("custlead sql exception"+e.getMessage());
        }
        NewDashBoard.lead(service,lead,user,name);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
        // TODO add your handling code here:
        jPanel2MouseClicked(null);
    }//GEN-LAST:event_jLabel57MouseClicked

    private void txtAdultKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdultKeyReleased
        // TODO add your handling code here:
        putTotal();
    }//GEN-LAST:event_txtAdultKeyReleased

    private void txtChildKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChildKeyReleased
        // TODO add your handling code here:
        putTotal();
    }//GEN-LAST:event_txtChildKeyReleased

    private void txtInfantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInfantKeyReleased
        // TODO add your handling code here:
        putTotal();
    }//GEN-LAST:event_txtInfantKeyReleased

    private void txtToMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtToMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtToMouseExited

    private void txtToFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtToFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToFocusGained

    private void txtToFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtToFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToFocusLost

    private void txtDaysFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDaysFocusGained
        // TODO add your handling code here:
        try{
        Date d1=new SimpleDateFormat("yyyy-mm-dd").parse(from=txtFrom.getDateStringOrSuppliedString("yyyy-mm-dd"));
        Date d2=new SimpleDateFormat("yyyy-mm-dd").parse(to=txtTo.getDateStringOrSuppliedString("yyyy-mm-dd"));
        txtDays.setText(ChronoUnit.DAYS.between(d1.toInstant(),d2.toInstant())+"");
            
        }
        catch(Exception e)
        {
            System.out.println("date exception");
        }
    }//GEN-LAST:event_txtDaysFocusGained

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        // TODO add your handling code here:
        jPanel3MouseClicked(null);
    }//GEN-LAST:event_jLabel60MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAirTicket;
    private javax.swing.JCheckBox cbHotel;
    private javax.swing.JCheckBox cbInsurance;
    private javax.swing.JCheckBox cbPassport;
    private javax.swing.JCheckBox cbRailwayTicket;
    private javax.swing.JCheckBox cbVehicle;
    private javax.swing.JCheckBox cbVise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAdult;
    private javax.swing.JTextField txtChild;
    private javax.swing.JTextField txtCity;
    private com.github.lgooddatepicker.components.DatePicker txtDate;
    private javax.swing.JTextField txtDays;
    private javax.swing.JTextField txtEmail;
    private com.github.lgooddatepicker.components.DatePicker txtFrom;
    private javax.swing.JTextField txtInfant;
    private javax.swing.JTextField txtLeadno;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtPasson;
    private javax.swing.JComboBox<String> txtPriority;
    private javax.swing.JTextField txtRef_account;
    private javax.swing.JTextField txtReference;
    private com.github.lgooddatepicker.components.DatePicker txtTo;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
public int getNewLead()
{
    int lead_no=0;
    String sql="insert into lead_increment values()";
    try{
    int result=DBConnection.executeUpdate(sql);
    if(result<=0)
    {
        System.out.println("new_invoice create invoice");
    }
    }
    catch(SQLException e)
    {
        System.out.println("dim createinvoice");
    }
    sql="select max(lead_no) from lead_increment";
    try{
    ResultSet rs=DBConnection.executeQuery(sql);
    if(rs.next())
    {
        lead_no=rs.getInt("max(lead_no)");
    }
    }
    catch(SQLException e)
    {
        System.out.println("create invoice second try");
    }
    return lead_no;
    }
public void putTotal()
{
    try{
        Integer.parseInt(txtInfant.getText());
        Integer.parseInt(txtChild.getText());
        Integer.parseInt(txtAdult.getText());
    }
    catch(Exception e)
    {
        return;
    }
    
    txtTotal.setText(Integer.parseInt(txtAdult.getText())+Integer.parseInt(txtChild.getText())+Integer.parseInt(txtInfant.getText())+"");
}
}
