
package project;
import Classdoc.DBConnection;
import Classdoc.Dim;
import java.awt.Dimension;
import javax.swing.DefaultCellEditor;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

public class hotelbooking extends javax.swing.JPanel {

    /**
     * Creates new form hotelbooking
     */
    public hotelbooking(String user,Dimension dim) {
        
        initComponents();
        this.setSize(dim);
        txtinvoiceno.setText("" + new Dim().createInvoice());
        txtuser.setText(user);
        jScrollPane1.setVisible(true);
        jPanel1.setVisible(true);
        ccb.addItem(" ");
        cbm.addItem(" ");
        try
        {
//        Class.forName("java.sql.Driver");
//        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
//        st=con.createStatement();
        String b,c,d,e;
        b="Select * from customer_details";
        rs=DBConnection.executeQuery(b);
        
        while(rs.next())
         {
        c=rs.getString("cname");
        ccb.addItem(c);
       }

        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage()+" msg of upper");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jc = new javax.swing.JComboBox<>();
        jc1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txthname = new javax.swing.JTextField();
        txtinvoiceno = new javax.swing.JTextField();
        ccb = new javax.swing.JComboBox<>();
        cbm = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        txtcid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        totalamount = new javax.swing.JTextField();
        txttax = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtdisc = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtc = new javax.swing.JTextField();
        txtinvoicedate = new com.github.lgooddatepicker.components.DatePicker();
        txtcheckout = new com.github.lgooddatepicker.components.DatePicker();
        txtcheckin = new com.github.lgooddatepicker.components.DatePicker();
        txthaddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();

        jc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single A/c", "Double A/c", "Non A/c single", "Non A/c double", " " }));

        jc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Breakfast", "Lunch", "Dinner", "All" }));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Hotel address");
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel2.setText("Customer name");
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel4.setText("InvoiceDate");
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel5.setText("Mobile no");
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel1.add(txthname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 210, 30));

        txtinvoiceno.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtinvoiceno, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 110, -1));

        ccb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ccbItemStateChanged(evt);
            }
        });
        ccb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccbActionPerformed(evt);
            }
        });
        jPanel1.add(ccb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, -1));

        cbm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmItemStateChanged(evt);
            }
        });
        jPanel1.add(cbm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, 20));

        jLabel6.setText("Check in date");
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, 30));

        jLabel7.setText("Check out date");
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, 30));

        txtpay.setEditable(false);
        txtpay.setBackground(new java.awt.Color(204, 204, 204));
        txtpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayActionPerformed(evt);
            }
        });
        jPanel1.add(txtpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 80, 20));

        txtcid.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 140, 20));

        jLabel16.setText("Total Tax");
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, -1, -1));

        jLabel17.setText("Total Amt");
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, -1, 20));

        jLabel18.setText("Topay:");
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, -1, -1));

        totalamount.setEditable(false);
        totalamount.setAutoscrolls(false);
        totalamount.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 80, -1));
        jPanel1.add(txttax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 80, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Room Type", "Meal", "Room/s", "Person/s", "Days", "Rate", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setGridColor(new java.awt.Color(255, 255, 255));
        table1.setIntercellSpacing(new java.awt.Dimension(3, 3));
        table1.setRowHeight(24);
        jScrollPane3.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jc));
            table1.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(jc1));
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1040, 100));

        jLabel19.setText("Customer-id");
        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        jLabel10.setText("Invoiceno");
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jButton1.setText("Add row");
        jButton1.setBackground(new java.awt.Color(54, 33, 89));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        jButton2.setText("Insert");
        jButton2.setBackground(new java.awt.Color(53, 33, 89));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 380, -1, -1));

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hotel Name", "Hotel Address", "no of person", "Roomtype", "No of Rooms", "Meal", "Check in date", "Check out date", "Rate", "Amount", "Days"
            }
        ));
        jt1.setRowHeight(20);
        jScrollPane4.setViewportView(jt1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1040, 110));

        jButton3.setText("CALCULATE");
        jButton3.setBackground(new java.awt.Color(53, 33, 89));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, -1, -1));

        jButton4.setText("Remove row");
        jButton4.setBackground(new java.awt.Color(53, 33, 89));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 120, -1));

        jLabel3.setText("Discount");
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, -1, -1));
        jPanel1.add(txtdisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 80, -1));

        jButton5.setText("Remove Row");
        jButton5.setBackground(new java.awt.Color(53, 33, 89));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 540, -1, -1));

        jButton6.setText("Confirm");
        jButton6.setBackground(new java.awt.Color(53, 33, 89));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, -1, -1));

        jLabel8.setText("User");
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        txtuser.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 100, -1));

        jLabel9.setText("Commission");
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, -1, -1));

        txtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcActionPerformed(evt);
            }
        });
        jPanel1.add(txtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 80, 20));
        jPanel1.add(txtinvoicedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 140, -1));
        jPanel1.add(txtcheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, -1, 30));
        jPanel1.add(txtcheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, -1, 30));
        jPanel1.add(txthaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 210, 30));

        jLabel11.setText("Hotel Name");
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator9.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1020, 10));

        jSeparator10.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator10.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1160, 10));

        jSeparator12.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator12.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 20, 230));

        jSeparator13.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator13.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 230));

        jSeparator11.setBackground(new java.awt.Color(54, 33, 89));
        jSeparator11.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1020, 10));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
Connection con =null;
 ResultSet  rs= null ;
 Statement st=null;
 String sql;     
 
    private void txtpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel t=(DefaultTableModel)table1.getModel(); 
       t.addRow(new Object[]{});
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ccbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ccbItemStateChanged
String b,e,f;
         int c,d;
         cbm.removeAllItems();
        e=(String) ccb.getSelectedItem(); 
        try
        {
//        Class.forName("java.sql.Driver");
//        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
//        st=con.createStatement();
       b="Select mobile_no from customer_details where cname ='"+e+"'";
        rs=DBConnection.executeQuery(b);
         while(rs.next())
         {
         f=rs.getString("mobile_no");
         cbm.addItem(f);
         }
         
}
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ccbItemStateChanged

    private void cbmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmItemStateChanged
String b,e,f;
         int c,d;
        e=(String) cbm.getSelectedItem(); 
        try
        {
//        Class.forName("java.sql.Driver");
//        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
//        st=con.createStatement();
       b="Select cid from customer_details where mobile_no ='"+e+"'";
        rs=DBConnection.executeQuery(b);
         while(rs.next())
         {
         c=rs.getInt("cid");
         txtcid.setText(""+c);
      }
         }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_cbmItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 DefaultTableModel t=(DefaultTableModel)table1.getModel();  
      DefaultTableModel t1=(DefaultTableModel)jt1.getModel();  
     
        int d,e1,f,g,amt,sum=0;
      String sql;
      String h1,h2,h3,h4;
      h1=txthname.getText();
      h2=txthaddress.getText();
      h3=txtcheckin.getDateStringOrSuppliedString("yyyy-mm-dd");
      h4=txtcheckout.getDateStringOrSuppliedString("yyyy-mm-dd");
        try
        {
        int row=table1.getRowCount();
        for(int i=0;i<=row;i++)
        {
          String a=(t.getValueAt(i,0)).toString(); //room type
          String b=(t.getValueAt(i,1)).toString(); // meals
          d=Integer.parseInt((t.getValueAt(i,2)).toString());  //rooms
          e1=Integer.parseInt((t.getValueAt(i,3)).toString());//persons
          f=Integer.parseInt((t.getValueAt(i,4)).toString());//days
          g=Integer.parseInt((t.getValueAt(i,5)).toString()); //rate
          amt=d*f*g;
          sum=sum+amt;
           System.out.println("i="+i+"amt="+amt);
          t.setValueAt(amt,i,6);
       t1.addRow(new Object[]{h1,h2,e1,a,d,b,h3,h4,g,amt,f});
        }
            }
        catch(Exception e)
        {
            System.out.println(""+e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 DefaultTableModel t1=(DefaultTableModel)jt1.getModel(); 
      int sum=0;
      int amt;
        try
     {
      int row=jt1.getRowCount();
      for(int i=0;i<=row;i++)
      {
      amt=Integer.parseInt((t1.getValueAt(i,9)).toString());
      sum=sum+amt;
      }
     }
     catch(Exception e1)
     {
         System.out.println(""+e1.getMessage());
     }
totalamount.setText(""+sum);
double a,b,c,d;
a=Double.parseDouble(txttax.getText());
b=Double.parseDouble(txtdisc.getText());
c=Double.parseDouble(totalamount.getText());
d=Double.parseDouble(txtc.getText());
c=c+a-b+d;
txtpay.setText(""+c);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
        DefaultTableModel t=(DefaultTableModel)table1.getModel();  
try
{
 int row=table1.getRowCount();
 --row;
t.removeRow(row);
}
catch(Exception e1)
{
JOptionPane.showMessageDialog(null, e1.getMessage());
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel t=(DefaultTableModel)jt1.getModel();  
try
{
 int row=jt1.getRowCount();
 --row;
t.removeRow(row);
}
catch(Exception e1)
{
JOptionPane.showMessageDialog(null, e1.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        payment();
        hotel();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcActionPerformed

    private void ccbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbm;
    private javax.swing.JComboBox<String> ccb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JComboBox<String> jc;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JTable jt1;
    private javax.swing.JTable table1;
    private javax.swing.JTextField totalamount;
    private javax.swing.JTextField txtc;
    private com.github.lgooddatepicker.components.DatePicker txtcheckin;
    private com.github.lgooddatepicker.components.DatePicker txtcheckout;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtdisc;
    private javax.swing.JTextField txthaddress;
    private javax.swing.JTextField txthname;
    private com.github.lgooddatepicker.components.DatePicker txtinvoicedate;
    private javax.swing.JTextField txtinvoiceno;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txttax;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
public void hotel()
{
try
{
Class.forName("java.sql.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
      st=con.createStatement();
      DefaultTableModel t=(DefaultTableModel)jt1.getModel();  

      int row=jt1.getRowCount();
      for(int i=0;i<row;i++)
      {
 sql="Insert into hotel values('"+txtcid.getText()+"','"+txtinvoiceno.getText()+"','"+txtinvoicedate.getDateStringOrSuppliedString("yyyy-mm-dd")+"','"+t.getValueAt(i,0)+"','"+t.getValueAt(i,1)+"','"+t.getValueAt(i,2)+"','"+t.getValueAt(i,3)+"','"+t.getValueAt(i,4)+"','"+t.getValueAt(i,5)+"','"+t.getValueAt(i,6)+"','"+t.getValueAt(i,7)+"','"+t.getValueAt(i,8)+"','"+t.getValueAt(i,9)+"','"+t.getValueAt(i,10)+"');";
 int result=DBConnection.executeUpdate(sql);
 if (result > 0) {
                DBConnection.commit();
                        // JOptionPane.showMessageDialog(null, "Record Saved Successfully");
            } else {
                //JOptionPane.showMessageDialog(null, "Sorry Fail to Save Record");
            }
 System.out.println(""+sql);
 //st.executeUpdate(sql);
      }
    }
catch(Exception ex)
{
    System.out.println(""+ex.getMessage());
}

}
    
    public void payment()
{
try
{
    double comm,amt;
    amt=Double.parseDouble(totalamount.getText());
    comm=Double.parseDouble(txtc.getText());
// Class.forName("java.sql.Driver");
//      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
//      st=con.createStatement();     
      sql="Insert into payment(invoiceno,invoicedate,cid,customername,actualamount,balance,user,discount,tax,commission) values('"+txtinvoiceno.getText()+"','"+txtinvoicedate.getDateStringOrSuppliedString("yyyy-mm-dd") + "','"+txtcid.getText()+"','"+ccb.getSelectedItem()+"','"+txtpay.getText()+"','"+txtpay.getText()+"','"+txtuser.getText()+"','"+txtdisc.getText()+"','"+txttax.getText()+"','"+comm+"');";
    int result=DBConnection.executeUpdate(sql);
if (result > 0) {
                DBConnection.commit();
                       //  JOptionPane.showMessageDialog(null, "Record Saved Successfully");
            } else {
               // JOptionPane.showMessageDialog(null, "Sorry Fail to Save Record");
            }  
    System.out.println(""+sql);
// st.executeUpdate(sql);

}
catch(Exception ex)
{
    System.out.println(""+ex.getMessage());
}
}
}
