/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classdoc.DBConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neeraj
 */
public class LeadSearch extends javax.swing.JPanel {

    /**
     * Creates new form LeadSearch
     */
    public LeadSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        btnSignup14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnSignup13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tab3 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        txtDate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(54, 33, 89));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        btnSignup14.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup14.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup14.setText("Close Tab");
        btnSignup14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnSignup14)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSignup14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 140, 40));

        jPanel5.setBackground(new java.awt.Color(54, 33, 89));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        btnSignup13.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup13.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup13.setText("Search");
        btnSignup13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnSignup13)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSignup13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 120, 40));

        tab3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tab3.setColumnSelectionAllowed(true);
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });
        tab3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tab3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tab3KeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(tab3);
        tab3.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 159, 1060, 570));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Lead Number");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Date:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 110, -1));
    }// </editor-fold>//GEN-END:initComponents
String date;
    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tab3MouseClicked

    private void tab3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab3KeyPressed

    }//GEN-LAST:event_tab3KeyPressed

    private void tab3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tab3KeyTyped

    private void btnSignup13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup13MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        date=txtDate.getDateStringOrSuppliedString("yyyy-mm-dd");
        System.out.println(date);
        String sql=String.format("select lead_no,t_name,mobile_no,email,city,address,n_adult,n_child,n_infant,l_from,l_to,n_days,priority,reference,reference_account from lead_details where dated='%s'", date);
        System.out.println(sql);
        try{
            ResultSet rs=DBConnection.executeQuery(sql);
            DefaultTableModel df=DBConnection.prepareTable(rs);
            tab3.setModel(df);
        }
        catch(SQLException e)
        {
            System.out.println(e+"lead search");
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void btnSignup14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup14MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignup11;
    private javax.swing.JLabel btnSignup12;
    private javax.swing.JLabel btnSignup13;
    private javax.swing.JLabel btnSignup14;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tab;
    private javax.swing.JTable tab1;
    private javax.swing.JTable tab3;
    private com.github.lgooddatepicker.components.DatePicker txtDate;
    // End of variables declaration//GEN-END:variables
}
