package project;


import Classdoc.DBConnection;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Neeraj
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        Dimension scrnSize = Toolkit.getDefaultToolkit().getScreenSize();
        Rectangle winSize = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        int taskBarHeight = scrnSize.height - winSize.height;
        Dimension dim=new Dimension((int)tk.getScreenSize().getWidth()/2,(int)(tk.getScreenSize().getHeight()-taskBarHeight)*2/3); 
        this.setSize(dim);
        this.setLocationRelativeTo(null);
        Dimension dim1=new Dimension((int)tk.getScreenSize().getWidth()/4,(int)(tk.getScreenSize().getHeight()-taskBarHeight)*2/3); 
        panellogin1.setPreferredSize(dim1);
        panellogin2.setPreferredSize(dim1);
        panellogin3.setVisible(false);
        jLabel13.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellogin1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panellogin2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panellogin3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnSignup2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnSignup3 = new javax.swing.JLabel();
        lblInvalid1 = new javax.swing.JLabel();
        emailInvalid1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblsignin = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtPwd = new javax.swing.JPasswordField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        chAgree = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        btnSignin = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        emailInvalid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblInvalid = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnSignup = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnSignup1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panellogin1.setBackground(new java.awt.Color(102, 255, 102));
        panellogin1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Dev Software Limited");
        panellogin1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, 50));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Take Your Business to Another Level With:");
        panellogin1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 320, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tms1.png"))); // NOI18N
        panellogin1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 300, 380));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        panellogin1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, 110));

        getContentPane().add(panellogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 360, 560));

        panellogin2.setBackground(new java.awt.Color(36, 47, 65));
        panellogin2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("FULL NAME");
        panellogin2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("PASSWORD");
        panellogin2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        panellogin3.setBackground(new java.awt.Color(36, 47, 65));
        panellogin3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 255, 102));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("EMAIL");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btnSignup2.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup2.setForeground(new java.awt.Color(102, 102, 102));
        btnSignup2.setText("SignIn");
        btnSignup2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup2MouseClicked(evt);
            }
        });
        jPanel5.add(btnSignup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 255, 102));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("EMAIL");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btnSignup3.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup3.setForeground(new java.awt.Color(102, 102, 102));
        btnSignup3.setText("SignUp");
        btnSignup3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup3MouseClicked(evt);
            }
        });
        jPanel6.add(btnSignup3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 150, 40));

        panellogin3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 40));

        lblInvalid1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInvalid1.setForeground(new java.awt.Color(255, 0, 0));
        panellogin3.add(lblInvalid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 250, 20));

        emailInvalid1.setForeground(new java.awt.Color(255, 0, 0));
        panellogin3.add(emailInvalid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 354, 270, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Contact :1234679165 ");
        panellogin3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Having Trouble? ");
        panellogin3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblsignin.setForeground(new java.awt.Color(204, 0, 0));
        panellogin3.add(lblsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, 20));

        panellogin2.add(panellogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 390, 280));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panellogin2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 110, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        panellogin2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 270, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        panellogin2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 270, 10));

        txtPwd.setBackground(new java.awt.Color(36, 47, 65));
        txtPwd.setForeground(new java.awt.Color(255, 255, 255));
        txtPwd.setBorder(null);
        txtPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPwdFocusGained(evt);
            }
        });
        txtPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwdActionPerformed(evt);
            }
        });
        panellogin2.add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 270, 30));

        txtName.setBackground(new java.awt.Color(36, 47, 65));
        txtName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        txtName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        panellogin2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 270, 30));

        txtEmail.setBackground(new java.awt.Color(36, 47, 65));
        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        panellogin2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 270, 30));

        chAgree.setBackground(new java.awt.Color(36, 47, 65));
        chAgree.setForeground(new java.awt.Color(255, 255, 255));
        chAgree.setText("I agree all terms of service");
        chAgree.setBorder(null);
        chAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAgreeActionPerformed(evt);
            }
        });
        panellogin2.add(chAgree, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("EMAIL");
        panellogin2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        btnSignin.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnSignin.setForeground(new java.awt.Color(204, 204, 204));
        btnSignin.setText("Already a member");
        btnSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSigninMouseClicked(evt);
            }
        });
        panellogin2.add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        panellogin2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 270, 10));

        emailInvalid.setForeground(new java.awt.Color(255, 0, 0));
        panellogin2.add(emailInvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 354, 270, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Sign in or Sign Up");
        panellogin2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-arrow.png"))); // NOI18N
        jLabel13.setAutoscrolls(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        panellogin2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        lblInvalid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInvalid.setForeground(new java.awt.Color(255, 0, 0));
        panellogin2.add(lblInvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 150, 20));

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("EMAIL");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btnSignup.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(102, 102, 102));
        btnSignup.setText("SignUp");
        jPanel3.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("EMAIL");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btnSignup1.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup1.setForeground(new java.awt.Color(102, 102, 102));
        btnSignup1.setText("SignUp");
        btnSignup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup1MouseClicked(evt);
            }
        });
        jPanel4.add(btnSignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 150, 40));

        panellogin2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 150, 40));

        getContentPane().add(panellogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -30, 470, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String name,pwd,email,sql;
    boolean check,evalid;
    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        toFront();
        if(!chAgree.isSelected())
            return;
        System.out.println("hey");
        name=txtName.getText().trim();
        pwd=String.valueOf(txtPwd.getPassword());
        email=txtEmail.getText().trim();
        System.out.println(name+pwd+email);
        //for email validation in order to tell user beforehand
        if(email.contains("@") && email.substring(email.indexOf(""+'@')).contains(".com"))
        {
            emailInvalid.setText("");
            evalid=true;
        }
        else
       {
           emailInvalid.setText("Invalid email..");
           evalid=false;
           return;
       }
        System.out.println("evalid="+evalid);
        
        //for name,pwd,email validation
        if(name.length()==0  || pwd.length()==0 || email.length()==0  ||!check  || !evalid || pwd.length()==0 )
        {
            lblInvalid.setText("All Fields are compulsary and should be valid");
            return;
        }
       
        signUp();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void btnSignup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void btnSigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSigninMouseClicked
        // TODO add your handling code here:
        panellogin3.setVisible(true);
        jLabel13.setVisible(true);
    }//GEN-LAST:event_btnSigninMouseClicked

    private void chAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chAgreeActionPerformed
        // TODO add your handling code here:
        if(chAgree.isSelected()==true)
        {
            check=true;
        }
    }//GEN-LAST:event_chAgreeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwdActionPerformed

    private void txtPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPwdFocusGained

    }//GEN-LAST:event_txtPwdFocusGained

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        toFront();
        name=txtName.getText().trim();
        pwd=String.valueOf(txtPwd.getPassword());
        if(name.length()==0 || pwd.length()==0)
        {
            lblsignin.setText("All fields are compulsary");
            return;
        }
        signIn();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void btnSignup3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup3MouseClicked

    private void btnSignup2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup2MouseClicked
        // TODO add your handling code here:
        jPanel5MouseClicked(null);
    }//GEN-LAST:event_btnSignup2MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        panellogin3.setVisible(false);
        jLabel13.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.getSystemLookAndFeelClassName();
                    break;
                }
         }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignin;
    private javax.swing.JLabel btnSignup;
    private javax.swing.JLabel btnSignup1;
    private javax.swing.JLabel btnSignup2;
    private javax.swing.JLabel btnSignup3;
    private javax.swing.JCheckBox chAgree;
    private javax.swing.JLabel emailInvalid;
    private javax.swing.JLabel emailInvalid1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblInvalid;
    private javax.swing.JLabel lblInvalid1;
    private javax.swing.JLabel lblsignin;
    private javax.swing.JPanel panellogin1;
    private javax.swing.JPanel panellogin2;
    private javax.swing.JPanel panellogin3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPwd;
    // End of variables declaration//GEN-END:variables

    private void signIn() {
        
        sql=String.format("select * from users Where lower(name)=lower('%s') and lower(password)=lower('%s') ", name,pwd);
        try
        {
            ResultSet rs=DBConnection.executeQuery(sql);
            if(rs.next())
            {
                new NewDashBoard(name).setVisible(true);
                this.dispose();
            }
            else
            {
                lblsignin.setText("Unable to sign in");
            }
        }
        catch(SQLException e)
        {
                 System.out.println("signin fn sqlexception login frame");
        }
    }

    private void signUp() {
        //check if user already exist
        sql=String.format("select * from users where lower(name)=lower('%s')", name);
        try
        {
            ResultSet rs=DBConnection.executeQuery(sql);
            if(rs.next())
            {
            lblInvalid.setText("user already exist");
            return;
            }
        }
        catch(SQLException e)
        {
            System.out.println("signup check if user already exist login frame");
        }
        //sign up user
        sql=String.format("Insert into users values('%s','%s','%s')", name,pwd,email);
        System.out.println(sql);
        try
        {
            int result=DBConnection.executeUpdate(sql);
            if(result>0)
            {
                lblInvalid.setText("");
                lblsignin.setText("");
                new NewDashBoard(name).setVisible(true);
                this.dispose();
                 
            }
        }
        catch(SQLException e)
        {
            System.out.println("Sqlexception in signup login frame");
        }
    }
}
