/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Dimension;

/**
 *
 * @author Neeraj
 */
public class Mail extends javax.swing.JPanel {

    /**
     * Creates new form Mail
     */
    public Mail(Dimension dim) {
        initComponents();
        this.setSize(dim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnSignup10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSignup11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSubject = new javax.swing.JTextArea();
        jLabel51 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        btnSignup10.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup10.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup10.setText("Close Tab");
        btnSignup10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnSignup10)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSignup10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, 120, 40));

        jPanel4.setBackground(new java.awt.Color(54, 33, 89));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        btnSignup11.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup11.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup11.setText("Send");
        btnSignup11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnSignup11)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSignup11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 110, 40));

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 880, 330));

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("Message");
        add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));
        add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 500, -1));

        jLabel50.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        jLabel50.setText("To:");
        add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        txtSubject.setColumns(20);
        txtSubject.setRows(5);
        jScrollPane2.setViewportView(txtSubject);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 500, -1));

        jLabel51.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 51, 51));
        jLabel51.setText("Subject:");
        add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
String to,subject,message;
    private void btnSignup10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup10MouseClicked
        // TODO add your handling code here:
        jPanel3MouseClicked(null);
    }//GEN-LAST:event_btnSignup10MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
    }//GEN-LAST:event_jPanel3MouseClicked

    private void btnSignup11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup11MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        to=txtTo.getText();
        subject=txtSubject.getText();
        message=txtMessage.getText();
        try{
        new Classdoc.SendEmail(to,subject,message);
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jPanel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignup10;
    private javax.swing.JLabel btnSignup11;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextArea txtSubject;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
