/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classdoc.DBConnection;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Neeraj
 */
public class NewCustomer extends javax.swing.JPanel {

    /**
     * Creates new form NewCustomer
     */
    public NewCustomer(Dimension dim) {
        initComponents();
        this.setSize(dim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hotelPanel = new javax.swing.JPanel();
        panel5 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtPincode = new javax.swing.JTextField();
        nMobile = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        nEmail = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        nAddress = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblError3 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        alternateNo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtError = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();

        hotelPanel.setBackground(new java.awt.Color(255, 255, 255));

        panel5.setBackground(new java.awt.Color(255, 255, 255));
        panel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 51));
        jLabel38.setText("Enter  Name:");
        panel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Pincode:");
        panel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 90, -1));
        panel5.add(txtPincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 270, 30));
        panel5.add(nMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 270, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("Enter Mobile Number:");
        panel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("Enter Customer Email:");
        panel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));
        panel5.add(nEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 270, 30));

        nAddress.setColumns(20);
        nAddress.setRows(5);
        jScrollPane4.setViewportView(nAddress);

        panel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 480, 160));

        jLabel44.setForeground(new java.awt.Color(204, 0, 0));
        jLabel44.setText("*");
        panel5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 20, -1));

        jLabel46.setForeground(new java.awt.Color(204, 0, 0));
        jLabel46.setText("*");
        panel5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 20, -1));

        jLabel47.setForeground(new java.awt.Color(204, 0, 0));
        jLabel47.setText("*");
        panel5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 20, -1));

        lblEmail.setForeground(new java.awt.Color(204, 0, 0));
        lblEmail.setText("*");
        panel5.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 150, 20));

        lblError3.setForeground(new java.awt.Color(255, 0, 0));
        panel5.add(lblError3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 230, 20));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 51, 51));
        jLabel45.setText("Enter Address:");
        panel5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 140, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("Alternate No:");
        panel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        jLabel50.setText("City:");
        panel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 110, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 51, 51));
        jLabel51.setText("State:");
        panel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, -1));
        panel5.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 270, 30));
        panel5.add(alternateNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 270, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 1));
        panel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1070, 10));

        jLabel52.setForeground(new java.awt.Color(204, 0, 0));
        jLabel52.setText("*");
        panel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 20, -1));

        jLabel53.setForeground(new java.awt.Color(204, 0, 0));
        jLabel53.setText("*");
        panel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 20, 30));

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });
        panel5.add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 270, 30));
        panel5.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 270, 30));

        jLabel56.setForeground(new java.awt.Color(204, 0, 0));
        jLabel56.setText("*");
        panel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 20, -1));

        jLabel57.setForeground(new java.awt.Color(204, 0, 0));
        jLabel57.setText("*");
        panel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 20, -1));

        txtError.setForeground(new java.awt.Color(255, 0, 0));
        panel5.add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 170, 20));

        jButton5.setBackground(new java.awt.Color(54, 33, 89));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 140, 40));

        Title.setBackground(new java.awt.Color(54, 33, 89));
        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man (1).png"))); // NOI18N
        Title.setText("Add Customer");
        Title.setOpaque(true);
        panel5.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1070, 90));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 1));
        panel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1070, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 1));
        panel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 500, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setPreferredSize(new java.awt.Dimension(0, 1));
        panel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1060, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setPreferredSize(new java.awt.Dimension(0, 1));
        panel5.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1070, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setPreferredSize(new java.awt.Dimension(0, 1));
        panel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 20, 270));

        jButton1.setBackground(new java.awt.Color(54, 33, 89));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        panel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 130, 40));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setPreferredSize(new java.awt.Dimension(0, 1));
        panel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 500, 10));

        javax.swing.GroupLayout hotelPanelLayout = new javax.swing.GroupLayout(hotelPanel);
        hotelPanel.setLayout(hotelPanelLayout);
        hotelPanelLayout.setHorizontalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelPanelLayout.createSequentialGroup()
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 180, Short.MAX_VALUE))
        );
        hotelPanelLayout.setVerticalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelPanelLayout.createSequentialGroup()
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1015, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(hotelPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
String name, mobile, email, address, sql, alternateno, city, pincode, state;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         state = txtState.getText();
        alternateno = alternateNo.getText();
        city = txtCity.getText();
        pincode = txtPincode.getText();
        name = txtName.getText();
        mobile = nMobile.getText();
        email = nEmail.getText();
        address = nAddress.getText();
        txtError.setText("");
        lblEmail.setText("");
        if (name.length() == 0 || mobile.length() == 0 || email.length() == 0 || address.length() == 0 || state.length() == 0 || alternateno.length() == 0 || pincode.length() == 0 || city.length() == 0) {
            txtError.setText("All Fields are Compulsary");
            return;
        }
        
        if (!(email.contains("@") && email.substring(email.indexOf("" + '@')).contains(".com"))) {
            lblEmail.setText("Enter valid Email");
            return;
        }
        txtError.setText("");
        lblEmail.setText("");
        //Check if Customer already exist
        sql = String.format("select * from customer_details where cname='%s'", name);
        System.out.println(sql);
        try {
            ResultSet rs = DBConnection.executeQuery(sql);
            if (rs.next()) {
                txtError.setText("Customer Already Exist");
                return;
            }
        } catch (SQLException e) {
            System.out.println("exception in searching if customer already exist");
        }
        //Add Customer
        sql = String.format("insert into customer_details(cname,address,mobile_no,email,alter_no,city,pincode,state) values('%s','%s','%s','%s','%s','%s','%s','%s')", name, address, mobile, email, alternateno, city, pincode, state);
        
        System.out.println(sql);
        try {
            int result = DBConnection.executeUpdate(sql);
            if (result > 0) {
                txtError.setText("");
                lblEmail.setText("");
            }
        } catch (SQLException e) {
            System.out.println("customer frame add and select customer sqlexception" + e.getMessage());
        }
        cleanup();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JTextField alternateNo;
    private javax.swing.JPanel hotelPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblError3;
    private javax.swing.JTextArea nAddress;
    private javax.swing.JTextField nEmail;
    private javax.swing.JTextField nMobile;
    private javax.swing.JPanel panel5;
    private javax.swing.JTextField txtCity;
    private javax.swing.JLabel txtError;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPincode;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables
public void cleanup() {
        txtName.setText("");
        alternateNo.setText("");
        txtCity.setText("");
        nAddress.setText("");
        txtPincode.setText("");
        txtState.setText("");
        nEmail.setText("");
        nMobile.setText("");
    }
    
}
