/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classdoc.DBConnection;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Neeraj
 */
public class SearchNew extends javax.swing.JPanel {

    /**
     * Creates new form SearchNew
     */
    public SearchNew(List ar,Dimension dim) {
        initComponents();
        this.setSize(dim);
        func();
        
        namePanel.setVisible(false);
        String ar1[]=new Classdoc.Dim().addCustomerMobileID(""+ar.get(0));
        cbName.setModel(new DefaultComboBoxModel(ar.toArray()));
        txtMobile.setText(ar1[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btn = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        btnSignup8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        btnSignup9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        cmbFirst = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtTab = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        namePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbName = new javax.swing.JComboBox<>();
        txtMobile = new javax.swing.JTextField();
        idPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCid = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnSignup10 = new javax.swing.JLabel();
        cbSecond = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn.setBackground(new java.awt.Color(54, 33, 89));
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
        });
        btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("EMAIL");
        btn.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btnSignup8.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup8.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup8.setText("Search");
        btnSignup8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup8MouseClicked(evt);
            }
        });
        btn.add(btnSignup8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -1, -1, 40));

        jPanel12.setBackground(new java.awt.Color(102, 255, 102));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("EMAIL");
        jPanel12.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btnSignup9.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup9.setForeground(new java.awt.Color(102, 102, 102));
        btnSignup9.setText("SignUp");
        btnSignup9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup9MouseClicked(evt);
            }
        });
        jPanel12.add(btnSignup9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btn.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 150, 40));

        jPanel1.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 130, 40));

        tab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tab);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1220, 400));

        cmbFirst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "railway_details", "vehicle_details", "airline", "hotel" }));
        cmbFirst.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFirstItemStateChanged(evt);
            }
        });
        cmbFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbFirstMouseClicked(evt);
            }
        });
        jPanel1.add(cmbFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 110, 20));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 260, 20));

        txtTab.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(txtTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 349, 112, 21));

        lblError.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 210, 20));

        namePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Customer Name");

        jLabel5.setText("Customer Mobile");

        cbName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNameItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbName, 0, 88, Short.MAX_VALUE)
                    .addComponent(txtMobile))
                .addContainerGap())
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(namePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 320, 90));

        idPanel.setBackground(new java.awt.Color(255, 255, 255));
        idPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Forgot");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        idPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 60, 20));

        jLabel2.setText("Cid");
        idPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cbCid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idPanel.add(cbCid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, -1));

        jPanel1.add(idPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 290, 90));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        btnSignup10.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup10.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup10.setText("Print");
        btnSignup10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(btnSignup10)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnSignup10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 120, 40));
        jPanel1.add(cbSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 110, -1));

        Title.setBackground(new java.awt.Color(54, 33, 89));
        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        Title.setText("Search");
        Title.setOpaque(true);
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1070, 90));

        jLabel6.setText("Invoice No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 111, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
int check1 = 0, check2 = 0;
    String cid, table, cname, mobile, invoiceno, date, sql,print;
    List<String> in = new ArrayList<>();
    DefaultTableModel df;
    private void btnSignup8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup8MouseClicked
        // TODO add your handling code here:
        btnMouseClicked(null);
    }//GEN-LAST:event_btnSignup8MouseClicked

    private void btnSignup9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup9MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel12MouseClicked

    private void btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseClicked
        // TODO add your handling code here:
        table = cmbFirst.getSelectedItem().toString();
        checkTab(table);
            invoiceno = cbSecond.getText();
            check2 = 0;

        if (check1 == 0) {
            cid = cbCid.getSelectedItem().toString();
            System.out.println(cid);
        } else {
            cname = cbName.getSelectedItem().toString();
            mobile = txtMobile.getText();
        }
        if (check1 == 0 && check2 == 0) {
            if (invoiceno.length() == 0) {
                sql = String.format("select %s from %s where cid=%s",print, table, cid);
            } else if (cid.length() == 0) {
                sql = String.format("select %s from %s where invoice_no=%s",print, table, invoiceno);
            } else {
                sql = String.format("select %s from %s where cid=%s and invoice_no=%s",print, table, cid, invoiceno);
            }
            System.out.println(sql);
        } else if (check1 == 0 && check2 == 1) {
            if (cid.length() == 0) {
                sql = String.format("select %s from %s where invoice_no in (select invoice_no from payment_details where invoice_date='%s')",print, table, date);
                System.out.println(sql);
            } else if (date.length() == 0) {
                sql = String.format("select %s from %s where invoice_no in (select invoice_no from payment_details where cid=%s )",print, table, cid);
                System.out.println(sql);
            } else {
                sql = String.format("select %s from %s where invoice_no in (select invoice_no from payment_details where cid=%s and invoice_date='%s')",print, table, cid, date);
                System.out.println(sql);
            }
        } else if (check1 == 1 && check2 == 0) {
            if (cname.length() == 0 || mobile.length() == 0) {
                sql = String.format("select %s from %s where invoice_no=%s ",print, table, invoiceno);
            }
            if (invoiceno.length() == 0) {
                sql = String.format("select %s from %s where cid in (select cid from customer_details where cname='%s' and mobile_no='%s') ",print, table, cname, mobile);
            } else {
                sql = String.format("select %s from %s where invoice_no=%s and cid in (select cid from customer_details where cname='%s' and mobile_no='%s') ",print, table, invoiceno, cname, mobile);
            }
        } else {
            sql = String.format("select %s from %s where invoice_no in (select invoice_no from payment_details where cid in (select cid from customer_details where cname='%s' and mobile_no='%s') and invoice_date='%s')",print, table, cname, mobile, date);
        }
        System.out.println(sql);
        try {
            ResultSet rs = DBConnection.executeQuery(sql);
            df=DBConnection.prepareTable(rs);
            tab.setModel(df);
        } catch (SQLException e) {
            System.out.println("search new");
        }
        new Classdoc.TableRowResize().funcResize(tab);
    }//GEN-LAST:event_btnMouseClicked

    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMouseEntered

    private void tabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabKeyPressed

    }//GEN-LAST:event_tabKeyPressed

    private void cmbFirstItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFirstItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFirstItemStateChanged

    private void cmbFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbFirstMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFirstMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        idPanel.setVisible(false);
        namePanel.setVisible(true);
        check1 = 1;
        //  namePanel.setLocation(idPanel.getX(),idPanel.getY());
        // idPanel.setLocation(-100,-100);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnSignup10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup10MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        MessageFormat header=new MessageFormat("header");
        MessageFormat footer=new MessageFormat("footer");
        try{
        tab.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void cbNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNameItemStateChanged
        // TODO add your handling code here:
        findMobile(cbName.getSelectedItem().toString());
    }//GEN-LAST:event_cbNameItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel btn;
    private javax.swing.JLabel btnSignup10;
    private javax.swing.JLabel btnSignup8;
    private javax.swing.JLabel btnSignup9;
    private javax.swing.JComboBox<String> cbCid;
    private javax.swing.JComboBox<String> cbName;
    private javax.swing.JTextField cbSecond;
    private javax.swing.JComboBox<String> cmbFirst;
    private javax.swing.JPanel idPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblError;
    private javax.swing.JPanel namePanel;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JLabel txtTab;
    // End of variables declaration//GEN-END:variables

    public void func()
    {
        ArrayList<Integer> arr=new ArrayList<>();
        String sql=String.format("select cid from customer_details");
        try{
        ResultSet rs=DBConnection.executeQuery(sql);
        while(rs.next())
        {
            arr.add(rs.getInt("cid"));
        }
                cbCid.setModel(new DefaultComboBoxModel(arr.toArray()));

        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }
 public void findMobile(String name)
 {
     String sql=String.format("select mobile_no from customer_details where cname='%s'", name);
     try{
     ResultSet rs=DBConnection.executeQuery(sql);
     if(rs.next())
     {
         txtMobile.setText(rs.getString("mobile_no"));
     }
     }
     catch(SQLException e)
     {
         System.out.println(e);
     }
 }
 public void checkTab(String table)
    {
        if(table.equals("railway_details"))
            print="invoice_no,invoice_date,type,passenger,ticket_no,pnr,train_no,t_date,time,rfrom,rto,class,amount,comm";
        else if(table.equals("vehicle_details"))
            print="invoice_no,invoice_date,type,passenger,bus_name,seat_no,t_date,time,vfrom,vto,class,amount,border_tax,comm";
        else if(table.equals("airline"))
            print="*";
        else 
            print="*";
    }
}

