/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class setting extends javax.swing.JPanel {

    /**
     * Creates new form setting
     */
    public setting(Dimension dim) {
        initComponents();
        this.setSize(dim);
        luser.setVisible(false);
        txtuserremove.setVisible(false);
         btnconform.setVisible(false);
         cbcid.addItem(" ");
        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
        st=con.createStatement();
        String b,c,d,e;
        sql="Select cid from customer_details";
        rs=st.executeQuery(sql);
        while(rs.next())
         {
        c=rs.getString("cid");
        cbcid.addItem(c);
       }
con.close();
        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage()+" msg of upper");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        luser = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        txtuser1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        txtpass1 = new javax.swing.JPasswordField();
        txtmobile = new javax.swing.JTextField();
        txtcustomeremail = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtuserremove = new javax.swing.JTextField();
        btnconform = new javax.swing.JButton();
        cbcid = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 90, 1030, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 980, 10));

        jButton1.setBackground(new java.awt.Color(54, 33, 89));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Change Password");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        jButton2.setBackground(new java.awt.Color(54, 33, 89));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 120, -1));

        jButton3.setBackground(new java.awt.Color(54, 33, 89));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Remove User");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Mobileno.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("State");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Old Password");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("New Password");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("User");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        luser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        luser.setText("User Name");
        add(luser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 110, -1));

        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuserFocusLost(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 90, -1));
        add(txtuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 90, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("User");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Password");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));
        add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 100, -1));
        add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 100, -1));
        add(txtpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 100, -1));
        add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 110, -1));
        add(txtcustomeremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 100, -1));

        txtstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstateActionPerformed(evt);
            }
        });
        add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 90, 20));
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 110, -1));

        jButton4.setBackground(new java.awt.Color(54, 33, 89));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Change Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Cid");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Email");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));
        add(txtuserremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, -1));

        btnconform.setBackground(new java.awt.Color(54, 33, 89));
        btnconform.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnconform.setForeground(new java.awt.Color(255, 255, 255));
        btnconform.setText("Conform");
        btnconform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconformActionPerformed(evt);
            }
        });
        add(btnconform, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        cbcid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbcidItemStateChanged(evt);
            }
        });
        add(cbcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 110, -1));

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 240, -1));

        jButton5.setBackground(new java.awt.Color(54, 33, 89));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Close Tab");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
Connection con =null;
 ResultSet  rs= null ;
 Statement st=null;
 String sql,pas;
    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
pas=new String(newpass.getPassword()); 
        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
        st=con.createStatement();
        String b,c,d,e;
        sql="Update  users set password='"+pas+"' where user ='"+ txtuser.getText()+"'";
        st.executeUpdate(sql);
            System.out.println(""+sql);
            con.close();
        }
         catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage()+" msg of upper");
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pas=new String(txtpass1.getPassword()); 
        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
        st=con.createStatement();
        String b,c,d,e;
        sql="Insert into  users values('"+txtuser1.getText()+"','"+pas+"','"+txtemail.getText()+"')";
        st.executeUpdate(sql);
            System.out.println(""+sql);
            con.close();
        }
         catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage()+" msg of upper");
        }        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        luser.setVisible(true);
        txtuserremove.setVisible(true);
        btnconform.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbcidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbcidItemStateChanged
        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
        st=con.createStatement();
        String b;
        sql="Select * from customer_details where cid='"+cbcid.getSelectedItem()+"'";
        rs=st.executeQuery(sql);
        while(rs.next())
         {
        b=rs.getString("cname");
        txtname.setText(b);
        b=rs.getString("mobile_no");
        txtmobile.setText(b);
        b=rs.getString("address");
        txtaddress.setText(b);
        b=rs.getString("city");
        txtcity.setText(b);
        b=rs.getString("state");
        txtstate.setText(b);
        b=rs.getString("email");
        txtemail.setText(b);
       }
con.close();
        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage()+" msg of upper");
        }
    }//GEN-LAST:event_cbcidItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
        st=con.createStatement();
        String b;
        sql="Update customer_details set cname='"+txtname.getText()+"',mobile_no='"+txtmobile.getText()+"',address='"+txtaddress.getText()+"',city='"+txtcity.getText()+"',email='"+txtcustomeremail.getText()+"',state='"+txtstate.getText()+"'  where cid='"+cbcid.getSelectedItem()+"'";
        st.executeUpdate(sql);
            System.out.println(""+sql);
        con.close();
        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage()+" msg of upper");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnconformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconformActionPerformed
try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/accountsoft", "root", "1234");
        st=con.createStatement();
        sql="Delete from  users where user ='"+txtuserremove.getText()+"' ";
        st.executeUpdate(sql);
            System.out.println(""+sql);
            con.close();
        }
         catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage()+" msg of upper");
        }        
              
    }//GEN-LAST:event_btnconformActionPerformed

    private void txtuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusGained
//txtuser.setBackground(java.awt.Color.CYAN);
    }//GEN-LAST:event_txtuserFocusGained

    private void txtuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusLost
//txtuser.setBackground(java.awt.Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserFocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        NewDashBoard.removeTab(this);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconform;
    private javax.swing.JComboBox<String> cbcid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel luser;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcustomeremail;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass1;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtuser;
    private javax.swing.JTextField txtuser1;
    private javax.swing.JTextField txtuserremove;
    // End of variables declaration//GEN-END:variables



}
