/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Utility.TabbedPaneUtility;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Neeraj
 */
public class VerticalPanel extends javax.swing.JPanel {
JTabbedPane BasePanel=null;
JPanel OptionPane=null;
    /**
     * Creates new form DashBoard
     */
    public VerticalPanel(JTabbedPane basePanel,JPanel optionPane,String u,List<String> ar) {
        initComponents();
        this.BasePanel=basePanel;
        user=u;
        arr=ar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        p11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(54, 33, 89));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBackground(new java.awt.Color(64, 43, 100));
        p1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man (1).png"))); // NOI18N
        p1.setText("        Customer");
        p1.setToolTipText("");
        p1.setOpaque(true);
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p1changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p1changeColorMouseExit(evt);
            }
        });
        add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 260, 50));

        p2.setBackground(new java.awt.Color(64, 43, 100));
        p2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aeroplane.png"))); // NOI18N
        p2.setText("         Flight       ");
        p2.setToolTipText("");
        p2.setOpaque(true);
        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p2changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p2changeColorMouseExit(evt);
            }
        });
        add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 50));

        p3.setBackground(new java.awt.Color(64, 43, 100));
        p3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p3.setForeground(new java.awt.Color(255, 255, 255));
        p3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/underground.png"))); // NOI18N
        p3.setText("         Railway    ");
        p3.setToolTipText("");
        p3.setOpaque(true);
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p3OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p3changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p3changeColorMouseExit(evt);
            }
        });
        add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 50));

        p4.setBackground(new java.awt.Color(64, 43, 100));
        p4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p4.setForeground(new java.awt.Color(255, 255, 255));
        p4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beach.png"))); // NOI18N
        p4.setText("        Hotel       ");
        p4.setToolTipText("");
        p4.setOpaque(true);
        p4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p4OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p4changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p4changeColorMouseExit(evt);
            }
        });
        add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 260, 50));

        p5.setBackground(new java.awt.Color(64, 43, 100));
        p5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p5.setForeground(new java.awt.Color(255, 255, 255));
        p5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus.png"))); // NOI18N
        p5.setText("        Vehicle     ");
        p5.setToolTipText("");
        p5.setOpaque(true);
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p5changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p5changeColorMouseExit(evt);
            }
        });
        add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 260, 50));

        p6.setBackground(new java.awt.Color(64, 43, 100));
        p6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p6.setForeground(new java.awt.Color(255, 255, 255));
        p6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        p6.setText("        Search      ");
        p6.setToolTipText("");
        p6.setOpaque(true);
        p6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p6changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p6changeColorMouseExit(evt);
            }
        });
        add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 260, 50));

        p7.setBackground(new java.awt.Color(64, 43, 100));
        p7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p7.setForeground(new java.awt.Color(255, 255, 255));
        p7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/credit-card.png"))); // NOI18N
        p7.setText("       Payment  ");
        p7.setToolTipText("");
        p7.setOpaque(true);
        p7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p7OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p7changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p7changeColorMouseExit(evt);
            }
        });
        add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 260, 50));

        p8.setBackground(new java.awt.Color(64, 43, 100));
        p8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p8.setForeground(new java.awt.Color(255, 255, 255));
        p8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bar-chart.png"))); // NOI18N
        p8.setText("       Statistics   ");
        p8.setToolTipText("");
        p8.setOpaque(true);
        p8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p8OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p8changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p8changeColorMouseExit(evt);
            }
        });
        add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 260, 50));

        p9.setBackground(new java.awt.Color(64, 43, 100));
        p9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p9.setForeground(new java.awt.Color(255, 255, 255));
        p9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard-paste-button.png"))); // NOI18N
        p9.setText("       Lead         ");
        p9.setToolTipText("");
        p9.setOpaque(true);
        p9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p9OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p9changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p9changeColorMouseExit(evt);
            }
        });
        add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 260, 50));

        p10.setBackground(new java.awt.Color(64, 43, 100));
        p10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p10.setForeground(new java.awt.Color(255, 255, 255));
        p10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        p10.setText("       LeadSearch");
        p10.setToolTipText("");
        p10.setOpaque(true);
        p10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p10OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p10changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p10changeColorMouseExit(evt);
            }
        });
        add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 260, 50));

        p11.setBackground(new java.awt.Color(64, 43, 100));
        p11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p11.setForeground(new java.awt.Color(255, 255, 255));
        p11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-account-box.png"))); // NOI18N
        p11.setText("        Accounts");
        p11.setToolTipText("");
        p11.setOpaque(true);
        p11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p11OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p11changeColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p11changeColorMouseExit(evt);
            }
        });
        add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 260, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account2.png"))); // NOI18N
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 70, 80));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 260, 10));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/opened-email-envelope.png"))); // NOI18N
        jLabel24.setToolTipText("Mail");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 40, 40));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bell-ring-alarm.png"))); // NOI18N
        jLabel27.setToolTipText("Reminder");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, 40, 40));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/feedback.png"))); // NOI18N
        jLabel26.setText("jLabel24");
        jLabel26.setToolTipText("Feedback");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 40, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        jLabel25.setText("jLabel24");
        jLabel25.setToolTipText("Settings");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 40, 40));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 260, 20));
    }// </editor-fold>//GEN-END:initComponents
String user;
List<String> arr;
    private void p1OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1OptionsMouseClicked
        // TODO add your handling code here:
                //NewDashBoard.newCustomer();
 TabbedPaneUtility.addTab("Customer", new NewCustomer(BasePanel.getSize()),"/images/boss.png");
    
    }//GEN-LAST:event_p1OptionsMouseClicked

    private void p1changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);
    }//GEN-LAST:event_p1changeColorMouseEntered

    private void p1changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p1changeColorMouseExit

    private void p2OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2OptionsMouseClicked
        // TODO add your handling code here:
               // NewDashBoard.newAirTicket();
TabbedPaneUtility.addTab("AirLine", new airticket(BasePanel.getSize(),user),"/images/airplane.png");
        
    }//GEN-LAST:event_p2OptionsMouseClicked

    private void p2changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p2changeColorMouseEntered

    private void p2changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p2changeColorMouseExit

    private void p3OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3OptionsMouseClicked
        // TODO add your handling code here:
                //NewDashBoard.newRailway();
//********************************************************************************************************
TabbedPaneUtility.addTab("Railway", new Railway(arr,user,BasePanel.getSize()),"/images/train.png");    
    }//GEN-LAST:event_p3OptionsMouseClicked

    private void p3changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p3changeColorMouseEntered

    private void p3changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p3changeColorMouseExit

    private void p4OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4OptionsMouseClicked
        // TODO add your handling code here:
                //NewDashBoard.newHotelBooking();
TabbedPaneUtility.addTab("Hotel", new hotelbooking(user,BasePanel.getSize()),"/images/hotel.png");
  
    }//GEN-LAST:event_p4OptionsMouseClicked

    private void p4changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p4changeColorMouseEntered

    private void p4changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p4changeColorMouseExit

    private void p5OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5OptionsMouseClicked
        // TODO add your handling code here:
                //NewDashBoard.newVehicle();
//TabbedPaneUtility.addTab("Accounts", new NewCustomer(BasePanel.getSize()),"/images/boss.png");
  TabbedPaneUtility.addTab("Vehicle", new Vehicle(arr,user,BasePanel.getSize()),"/images/school-bus.png");
    }//GEN-LAST:event_p5OptionsMouseClicked

    private void p5changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p5changeColorMouseEntered

    private void p5changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p5changeColorMouseExit

    private void p6OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6OptionsMouseClicked
        // TODO add your handling code here:
               // NewDashBoard.newSearch();
TabbedPaneUtility.addTab("Search", new SearchNew(arr,BasePanel.getSize()),"/images/se.png");
    }//GEN-LAST:event_p6OptionsMouseClicked

    private void p6changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p6changeColorMouseEntered

    private void p6changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p6changeColorMouseExit

    private void p7OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7OptionsMouseClicked
        // TODO add your handling code here:
//                NewDashBoard.newPayment();
                JLabel lbl=(JLabel)evt.getSource();
                TabbedPaneUtility.addTab("Payment", new payment(user,BasePanel.getSize()),"/images/cc.png");
  

    }//GEN-LAST:event_p7OptionsMouseClicked

    private void p7changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p7changeColorMouseEntered

    private void p7changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p7changeColorMouseExit

    private void p8OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8OptionsMouseClicked
        // TODO add your handling code here:
             //   NewDashBoard.newStats();
TabbedPaneUtility.addTab("Statistics", new StatsPanel(user,BasePanel.getSize()),"/images/diagram.png");
  
    }//GEN-LAST:event_p8OptionsMouseClicked

    private void p8changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p8changeColorMouseEntered

    private void p8changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p8changeColorMouseExit

    private void p9OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9OptionsMouseClicked
        // TODO add your handling code here:
           //     NewDashBoard.newCustLead();

    }//GEN-LAST:event_p9OptionsMouseClicked

    private void p9changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p9changeColorMouseEntered

    private void p9changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p9changeColorMouseExit

    private void p10OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p10OptionsMouseClicked
        // TODO add your handling code here:
         //       NewDashBoard.newLeadSearch();

    }//GEN-LAST:event_p10OptionsMouseClicked

    private void p10changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p10changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p10changeColorMouseEntered

    private void p10changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p10changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p10changeColorMouseExit

    private void p11OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p11OptionsMouseClicked
        // TODO add your handling code here:
        TabbedPaneUtility.addTab("Accounts", new Account(BasePanel.getSize()),"/images/salesman.png");
        //        NewDashBoard.newAccount();

    }//GEN-LAST:event_p11OptionsMouseClicked

    private void p11changeColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p11changeColorMouseEntered
        // TODO add your handling code here:
        setColor(evt);

    }//GEN-LAST:event_p11changeColorMouseEntered

    private void p11changeColorMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p11changeColorMouseExit
        // TODO add your handling code here:
        resetColor(evt);
    }//GEN-LAST:event_p11changeColorMouseExit

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
       // NewDashBoard.newMail();
       TabbedPaneUtility.addTab("Mail", new Mail(BasePanel.getSize()),"/images/boss.png");
  
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
               // NewDashBoard.newFeedback();
TabbedPaneUtility.addTab("Feedback", new Feedback(BasePanel.getSize()),"/images/boss.png");
  
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
             //   NewDashBoard.newSettings();
TabbedPaneUtility.addTab("Setting", new setting(BasePanel.getSize()),"/images/settings_480px.png");
  
    }//GEN-LAST:event_jLabel25MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p10;
    private javax.swing.JLabel p11;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    // End of variables declaration//GEN-END:variables
public void setColor(java.awt.event.MouseEvent evt) {
        evt.getComponent().setBackground(new java.awt.Color(85, 65, 118));
    }

    public void resetColor(java.awt.event.MouseEvent evt) {
        evt.getComponent().setBackground(new java.awt.Color(64, 43, 100));
    }
}
