/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InnerLeads;

import Classdoc.DBConnection;
import java.sql.SQLException;

/**
 *
 * @author Neeraj
 */
public class InsuranceLead extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceLead
     */
    public InsuranceLead(int n,String user,String name)
    {
        this();
        lead=n;
    }
    public InsuranceLead() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInsuranceType = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        jLabel48 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtPassonTo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSignup10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 51, 51));
        jLabel46.setText("Status");
        add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, -1, -1));

        jLabel47.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setText("Insurance Type");
        add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        txtInsuranceType.setColumns(20);
        txtInsuranceType.setRows(5);
        jScrollPane1.setViewportView(txtInsuranceType);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 580, 260));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 580, 140));

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("Notes");
        add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 580, -1));

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("Passon to");
        add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));
        add(txtPassonTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 580, -1));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignup10.setText("Save");
        btnSignup10.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup10.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup10MouseClicked(evt);
            }
        });
        jPanel2.add(btnSignup10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 100, 40));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 130, 20));
    }// </editor-fold>//GEN-END:initComponents
int lead;
String insurancetype,notes,passonto,status;
    private void btnSignup10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup10MouseClicked
        // TODO add your handling code here:
        jPanel2MouseClicked(null);
    }//GEN-LAST:event_btnSignup10MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        insurancetype=txtInsuranceType.getText();
        notes=txtNotes.getText();
        passonto=txtPassonTo.getText();
        status=txtStatus.getText();
        
        if(insurancetype.length()==0 || notes.length()==0)
        {
        jLabel1.setText("enter necessary details");
        return;
        }
        
        jLabel1.setText("");
        
        String sql=String.format("insert into insurance_lead values(%s,'%s','%s','%s','%s')",lead, insurancetype,notes,passonto,status);
        System.out.println(sql);
        try{
        int result=DBConnection.executeUpdate(sql);
        if(result<0)
        {
            System.out.println("something wrong in insurancelead");
            return;
        }
        jLabel1.setText("saved");
        }
        catch(SQLException e)
        {
            System.out.println(e+"insurance lead");
        }
    }//GEN-LAST:event_jPanel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignup10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtInsuranceType;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtPassonTo;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
