/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InnerLeads;

import Classdoc.DBConnection;
import java.sql.SQLException;

/**
 *
 * @author Neeraj
 */
public class RailwayLead extends javax.swing.JPanel {

    /**
     * Creates new form HotelLead
     */
    public RailwayLead(int n,String user,String name)
    {
        this();
    lead=n;
    }
    public RailwayLead() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel48 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtSector = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        txtQuota = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        jLabel56 = new javax.swing.JLabel();
        txtBerth = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        txtPassonTo = new javax.swing.JTextField();
        cbJourney = new javax.swing.JComboBox<>();
        txtTicket = new javax.swing.JTextField();
        cbClass = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnSignup10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("Status");
        add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, -1, -1));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 420, -1));

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("Journey");
        add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel50.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        jLabel50.setText("Sector");
        add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));
        add(txtSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 420, -1));

        jLabel52.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 51));
        jLabel52.setText("No. of Tickets");
        add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));
        add(txtQuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 420, -1));

        jLabel53.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 51, 51));
        jLabel53.setText("Class");
        add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel54.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 51, 51));
        jLabel54.setText("Quota");
        add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel55.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(51, 51, 51));
        jLabel55.setText("Berth");
        add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane1.setViewportView(txtNotes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 420, 70));

        jLabel56.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(51, 51, 51));
        jLabel56.setText("Notes");
        add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));
        add(txtBerth, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 420, -1));

        jLabel57.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(51, 51, 51));
        jLabel57.setText("Passon to");
        add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));
        add(txtPassonTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 420, -1));

        cbJourney.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Return", " " }));
        add(cbJourney, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 420, -1));
        add(txtTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 420, -1));

        cbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Class", "Second Class", "Third Class", "Passenger", " " }));
        add(cbClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 420, -1));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignup10.setText("Save");
        btnSignup10.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup10.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup10MouseClicked(evt);
            }
        });
        jPanel2.add(btnSignup10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 100, 40));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 130, 20));
    }// </editor-fold>//GEN-END:initComponents
int lead,tickets;
String journey,sector,r_class,quota,berth,notes,passonto,status;
    private void btnSignup10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup10MouseClicked
        // TODO add your handling code here:
        jPanel2MouseClicked(null);
    }//GEN-LAST:event_btnSignup10MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        journey=cbJourney.getSelectedItem().toString();
        sector=txtSector.getText();
        r_class=cbClass.getSelectedItem().toString();
        quota=txtQuota.getText();
        berth=txtBerth.getText();
        notes=txtNotes.getText();
        status=txtStatus.getText();
        
        if(sector.length()==0 || txtTicket.getText().length()==0 || quota.length()==0 || berth.length()==0 || notes.length()==0 || status.length()==0)
        {
        jLabel1.setText("Enter compulsary fields");
        return;
        }
       
        try{
       tickets=Integer.parseInt(txtTicket.getText());     
        }
        catch(NumberFormatException e)
        {
         jLabel1.setText(e.getMessage());
         return;
        }
        
        jLabel1.setText("");
        
        
        String sql=String.format("insert into railway_lead values(%s,'%s','%s',%s,'%s','%s','%s','%s','%s','%s')", lead,journey,sector,tickets,r_class,quota,berth,notes,passonto,status);
        System.out.println(sql);
        try{
        int result=DBConnection.executeUpdate(sql);
        if(result<0)
        {
            System.out.println("something went wrong");
            return;
        }
        jLabel1.setText("Saved");
        }
        catch(SQLException e)
        {
            System.out.println(e+"railway lead");
        }
    }//GEN-LAST:event_jPanel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignup10;
    private javax.swing.JComboBox<String> cbClass;
    private javax.swing.JComboBox<String> cbJourney;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBerth;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtPassonTo;
    private javax.swing.JTextField txtQuota;
    private javax.swing.JTextField txtSector;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTicket;
    // End of variables declaration//GEN-END:variables
}
