/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InnerLeads;

import Classdoc.DBConnection;
import java.sql.SQLException;

/**
 *
 * @author Neeraj
 */
public class VehicleLead extends javax.swing.JPanel {

    /**
     * Creates new form HotelLead
     */
    public VehicleLead(int n,String user,String name)
    {
        this();
    lead=n;
    }
    public VehicleLead() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel48 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtTripTax = new javax.swing.JTextField();
        txtCouchType = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtPassonTo = new javax.swing.JTextField();
        cbVehicle = new javax.swing.JComboBox<>();
        cbJourney = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnSignup10 = new javax.swing.JLabel();
        cbCity = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("Status");
        add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 420, -1));

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("Journey");
        add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel50.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        jLabel50.setText("City");
        add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel52.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 51));
        jLabel52.setText("Vehicle");
        add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel53.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 51, 51));
        jLabel53.setText("Trip Tax");
        add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel54.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 51, 51));
        jLabel54.setText("Couch Type");
        add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));
        add(txtTripTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 420, -1));
        add(txtCouchType, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 420, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane1.setViewportView(txtNotes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 420, 70));

        jLabel56.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(51, 51, 51));
        jLabel56.setText("Notes");
        add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        jLabel57.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(51, 51, 51));
        jLabel57.setText("Passon to");
        add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));
        add(txtPassonTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 420, -1));

        cbVehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 420, -1));

        cbJourney.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Return", " " }));
        add(cbJourney, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 420, -1));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignup10.setText("Save");
        btnSignup10.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSignup10.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup10MouseClicked(evt);
            }
        });
        jPanel2.add(btnSignup10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 100, 40));

        cbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 420, -1));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 130, 20));
    }// </editor-fold>//GEN-END:initComponents
int lead;
String journey,city,vehicle,triptax,couchtype,notes,passonto,status;
    private void btnSignup10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup10MouseClicked
        // TODO add your handling code here:
        jPanel2MouseClicked(null);
    }//GEN-LAST:event_btnSignup10MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

        journey=cbJourney.getSelectedItem().toString();
        city=cbCity.getSelectedItem().toString();
        vehicle=cbVehicle.getSelectedItem().toString();
        triptax=txtTripTax.getText();
        couchtype=txtCouchType.getText();
        notes=txtNotes.getText();
        passonto=txtPassonTo.getText();
        status=txtStatus.getText();
        
        if(triptax.length()==0 || couchtype.length()==0)
        {
            jLabel1.setText("Enter compulsary details");
            return;
        }
        
        String sql=String.format("insert into vehicle_lead values(%s,'%s','%s','%s',%s,'%s','%s','%s','%s')", lead,journey,city,vehicle,triptax,couchtype, notes,passonto,status);
        System.out.println(sql);
        try{
        int result=DBConnection.executeUpdate(sql);
        if(result<0)
        {
            System.out.println("something went wrong");
            return;
        }
        jLabel1.setText("saved");
        }
        catch(SQLException e)
        {
            System.out.println(e+"vehiclelead");
        }
    }//GEN-LAST:event_jPanel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignup10;
    private javax.swing.JComboBox<String> cbCity;
    private javax.swing.JComboBox<String> cbJourney;
    private javax.swing.JComboBox<String> cbVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCouchType;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtPassonTo;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTripTax;
    // End of variables declaration//GEN-END:variables
}
